spring.application.name=timetracker

# Database configuration using environment variables with defaults
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/timetrackerdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}


# JPA / Hibernate configuration
#create to drop and recreate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.github.clientId=Ov23livY1rWgeL0wmOPN
spring.security.oauth2.client.registration.github.clientSecret=9d8150584c5cc22a96d95485678839b587e89760
spring.security.oauth2.client.registration.github.scope=read:user, user:email, repo
