spring.application.name=timetracker

spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=4h
# spring.session.timeout=4h
spring.security.oauth2.client.registration.github.scope=read:user, user:email, repo
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized