# local postgres database configuration for development environment
spring.datasource.url=jdbc:postgresql://localhost:5432/timetrackerdb
spring.datasource.username=postgres
spring.datasource.password=password
server.forward-headers-strategy=framework
# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.client.registration.github.clientId=${DEV_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.clientSecret=${DEV_GITHUB_CLIENT_SECRET}

