import cz.cvut.fel.thesis.model.Issue;
import cz.cvut.fel.thesis.model.Session;
import cz.cvut.fel.thesis.model.TimeBlock;
import cz.cvut.fel.thesis.service.FormatService;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class FormatServiceTest {

    private FormatService formatService;
    private ZoneId testZoneId;

    @BeforeEach
    void setUp() {
        formatService = new FormatService();
        testZoneId = ZoneId.of("Europe/Prague");
    }

    @Nested
    class BuildSessionComments {

        @Test
        void buildsReport_WithSyncedSessions_SortedAndFormatted() {
            // ARRANGE
            Issue issue = new Issue();
            
            // 1. Session (Older, with notes)
            Session s1 = mock(Session.class);
            when(s1.isSynced()).thenReturn(true);
            when(s1.getCreatedAt()).thenReturn(Instant.parse("2026-04-01T10:00:00Z"));
            when(s1.getDuration()).thenReturn(Duration.ofHours(1).plusMinutes(30).plusSeconds(15));
            when(s1.getNotes()).thenReturn("session notes");
            
            TimeBlock tb1 = mock(TimeBlock.class);
            when(tb1.getStartDate()).thenReturn(Instant.parse("2026-04-01T10:00:00Z"));
            when(s1.getMostRecentTimeBlock()).thenReturn(tb1);

            // 2. Session (Newer, without notes - null)
            Session s2 = mock(Session.class);
            when(s2.isSynced()).thenReturn(true);
            when(s2.getCreatedAt()).thenReturn(Instant.parse("2026-04-02T15:00:00Z"));
            when(s2.getDuration()).thenReturn(Duration.ofHours(0).plusMinutes(45).plusSeconds(0));
            when(s2.getNotes()).thenReturn(null);
            
            TimeBlock tb2 = mock(TimeBlock.class);
            when(tb2.getStartDate()).thenReturn(Instant.parse("2026-04-02T15:00:00Z"));
            when(s2.getMostRecentTimeBlock()).thenReturn(tb2);

            // 3. Session (Unsynced - should not appear in the report!)
            Session unsyncedSession = mock(Session.class);
            when(unsyncedSession.isSynced()).thenReturn(false);

            // We mix the order in the list to test sorting
            issue.setSessions(List.of(s2, unsyncedSession, s1));

            String expectedReport = "Autogenerated report by Timetracker:\n\n" +
                    "• 2026-04-01 — Duration: 01h:30m — session notes\n" +
                    "• 2026-04-02 — Duration: 00h:45m\n";

            // ACT
            String result = formatService.buildSessionComments(issue, testZoneId);

            // ASSERT
            assertEquals(expectedReport, result);
        }

        @Test
        void buildsReport_WithBlankNotes_IgnoresNotesFormatting() {
            // ARRANGE
            Issue issue = new Issue();
            
            Session s1 = mock(Session.class);
            when(s1.isSynced()).thenReturn(true);
            when(s1.getCreatedAt()).thenReturn(Instant.parse("2026-04-01T10:00:00Z"));
            when(s1.getDuration()).thenReturn(Duration.ofHours(2).plusMinutes(0).plusSeconds(0));
            
            // Note is an empty string, so extra dash should not be shown
            when(s1.getNotes()).thenReturn("   "); 
            
            TimeBlock tb1 = mock(TimeBlock.class);
            when(tb1.getStartDate()).thenReturn(Instant.parse("2026-04-01T10:00:00Z"));
            when(s1.getMostRecentTimeBlock()).thenReturn(tb1);

            issue.setSessions(List.of(s1));

            String expectedReport = "Autogenerated report by Timetracker:\n\n" +
                    "• 2026-04-01 — Duration: 02h:00m\n";

            // ACT
            String result = formatService.buildSessionComments(issue, testZoneId);

            // ASSERT
            assertEquals(expectedReport, result);
        }

        @Test
        void buildsReport_WithNoSyncedSessions_ReturnsOnlyHeader() {
            // ARRANGE
            Issue issue = new Issue();
            
            Session unsyncedSession = mock(Session.class);
            when(unsyncedSession.isSynced()).thenReturn(false);
            
            issue.setSessions(List.of(unsyncedSession));

            String expectedReport = "Autogenerated report by Timetracker:\n\n";

            // ACT
            String result = formatService.buildSessionComments(issue, testZoneId);

            // ASSERT
            assertEquals(expectedReport, result);
        }
    }

    @Nested
    class BuildNewComment {

        @Test
        void formatsSingleSession_WithNotes() {
            // ARRANGE
            Session session = mock(Session.class);
            TimeBlock tb = mock(TimeBlock.class);
            
            when(tb.getStartDate()).thenReturn(Instant.parse("2026-04-05T12:00:00Z"));
            when(session.getMostRecentTimeBlock()).thenReturn(tb);

            Duration duration = Duration.ofHours(3).plusMinutes(5).plusSeconds(9);
            String notes = "Completed refactoring";

            String expectedReport = "Autogenerated report by Timetracker: \n" +
                    "• 2026-04-05 — Duration: 03h:05m — Completed refactoring\n";

            // ACT
            String result = formatService.buildNewComment(session, notes, duration, testZoneId);

            // ASSERT
            assertEquals(expectedReport, result);
        }

        @Test
        void formatsSingleSession_WithoutNotes() {
            // ARRANGE
            Session session = mock(Session.class);
            TimeBlock tb = mock(TimeBlock.class);
            
            when(tb.getStartDate()).thenReturn(Instant.parse("2026-04-05T12:00:00Z"));
            when(session.getMostRecentTimeBlock()).thenReturn(tb);

            Duration duration = Duration.ofHours(0).plusMinutes(12).plusSeconds(30);

            // Note is null
            String expectedReport = "Autogenerated report by Timetracker: \n" +
                    "• 2026-04-05 — Duration: 00h:12m\n";

            // ACT
            String result = formatService.buildNewComment(session, null, duration, testZoneId);

            // ASSERT
            assertEquals(expectedReport, result);
        }
    }
}