package cz.cvut.fel.thesis.service;

import cz.cvut.fel.thesis.model.Issue;
import cz.cvut.fel.thesis.model.Session;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Comparator;

/**
 * Builds human-readable text for exported or synchronized time tracking data.
 */
@Service
public class FormatService {

    /**
     * Builds a formatted comment body for a collection of synced sessions.
     *
     * @param issue issue whose sessions are being formatted
     * @param userZoneId user time zone
     * @return formatted GitHub comment body
     */
    public String buildSessionComments(Issue issue, ZoneId userZoneId){
        StringBuilder sb = new StringBuilder();
        sb.append("Autogenerated report by Timetracker:\n\n");

        issue.getSessions().stream()
                .filter(Session::isSynced)
                .sorted(Comparator.comparing(Session::getCreatedAt))
                .forEach(session -> {
                    Duration duration = session.getDuration();
                    sb.append("• ")
                            .append(session.getMostRecentTimeBlock().getStartDate().atZone(userZoneId).toLocalDate())
                            .append(" — Duration: ")
                            .append(formatDuration(duration));
                    if (session.getNotes() != null && !session.getNotes().isBlank()) {
                        sb.append(" — ").append(session.getNotes());
                    }
                    sb.append("\n");

                });

        return sb.toString();
    }

    /**
     * Builds a formatted comment body for an issue with no previously synced sessions
     *
     * @param toSync session to format
     * @param notes optional notes text
     * @param duration tracked duration
     * @param userZoneId user time zone
     * @return formatted GitHub comment body
     */
    public String buildNewComment(Session toSync, String notes, Duration duration, ZoneId userZoneId){
        StringBuilder sb = new StringBuilder();
        sb.append("Autogenerated report by Timetracker: \n");
        sb.append("• ")
                .append(toSync.getMostRecentTimeBlock().getStartDate().atZone(userZoneId).toLocalDate())
                .append(" — Duration: ")
                .append(formatDuration(duration));
        if (notes != null) {
            sb.append(" — ").append(notes);
        }
        sb.append("\n");

        return sb.toString();
    }

    public String formatDuration(Duration duration) {
        return String.format("%02dh:%02dm", duration.toHours(), duration.toMinutesPart());
    }
}
