package cz.cvut.fel.thesis.service;

import cz.cvut.fel.thesis.model.Issue;
import cz.cvut.fel.thesis.model.Session;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.Instant;
import java.time.ZoneId;
import java.util.Comparator;

@Service
public class FormatService {

    public String buildSessionComments(Issue issue, ZoneId userZoneId){
        StringBuilder sb = new StringBuilder();
        sb.append("Autogenerated report by Timetracker:\n\n");

        issue.getSessions().stream()
        //TODO: tady kouknout jestli ma byt synced
                .sorted(Comparator.comparing(Session::getCreatedAt))
                .forEach(session -> {
                    Duration duration = session.getDuration();
                    sb.append("• ")
                            .append(session.getMostRecentTimeBlock().getStartDate().atZone(userZoneId).toLocalDate())
                            .append(" — Duration: ")
                            .append(String.format("%02dh:%02dm:%02ds", duration.toHours(), duration.toMinutesPart(), duration.toSecondsPart()));
                    if (session.getNotes() != null && !session.getNotes().isBlank()) {
                        sb.append(" — ").append(session.getNotes());
                    }
                    sb.append("\n");

                });

        return sb.toString();
    }

    public String buildNewComment(Session toSync, String notes, Duration duration, ZoneId userZoneId){
        StringBuilder sb = new StringBuilder();
        sb.append("Autogenerated report by Timetracker: \n");
        sb.append("• ")
                .append(toSync.getMostRecentTimeBlock().getStartDate().atZone(userZoneId).toLocalDate())
                .append(" — Duration: ")
                .append(String.format("%02dh:%02dm:%02ds", duration.toHours(), duration.toMinutesPart(), duration.toSecondsPart()));
        if (notes != null) {
            sb.append(" — ").append(notes);
        }
        sb.append("\n");

        return sb.toString();
    }

    public String formatDuration(Duration duration) {
        return String.format("%02dh:%02dm:%02ds", duration.toHours(), duration.toMinutesPart(), duration.toSecondsPart());
    }
}
