services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timetrackerdb
#    ports:
#      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  springboot-api:
    build: ./springboot-api
    container_name: springboot-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/timetrackerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      DEV_GITHUB_CLIENT_ID: ${DEV_GITHUB_CLIENT_ID}
      DEV_GITHUB_CLIENT_SECRET: ${DEV_GITHUB_CLIENT_SECRET}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_REDIRECT_URI: http://localhost:3000/api/login/oauth2/code/github
    depends_on:
      - postgres

  react-app:
    build: ./react-app
    container_name: react-app
    ports:
      - "3000:80"
    depends_on:
       - springboot-api
    environment:
       - BACKEND_URL=http://springboot-api:8080/
volumes:
  pgdata:
